### ISSUE TITLE
Generic landing page

### ISSUE THREAD

**Issue by DMAN28** [DMAN28/jimmy-clips#5]
- [x] Create header with a short book me description
- [x] Our staff header with description
- [x] Barber 1 card
- [x] Barber 1 image
- [x] Barber 1 description
- [x] Barber 2 card
- [x] Barber 2 image 
- [x] Barber 2 description
- [x] #4  Add address
- [x] #4 add phone 
- [x] #4 add email 
- [x] #4 add social media 
- [x] #4 add booking links
- [ ] #4 make the forum send message to email
